import type { EntityType, Freshness } from '../core/types'

/**
 * Machine-readable source registry. Every layer, feed and basemap references one of these ids so
 * the UI can always say where a value came from. Human-oriented evidence lives in docs/DATA_SOURCES.md.
 */

/** Legal status, following docs/LICENSES_AND_ATTRIBUTIONS.md. */
export type LicenseStatus =
  | 'open-data' // explicit open licence (CC BY, ODbL, public domain…)
  | 'licensed-redistribution' // explicit terms that allow our use (possibly non-commercial)
  | 'publicly-accessible' // reachable without auth but no licence published / "all rights reserved"
  | 'unknown'

export type Access =
  | 'direct' // browser calls upstream (CORS allowed, no secret)
  | 'proxy' // goes through our /api proxy (no CORS, secret key, or to protect upstream)
  | 'snapshot' // copied at build time into public/data by scripts/fetch-static.ts
  | 'tiles' // imagery / terrain tiles streamed by Cesium

export interface DataSource {
  id: string
  name: string
  organization: string
  /** Human-facing page for the source. */
  url: string
  /** Endpoint pattern actually used (no secrets). */
  endpoint: string
  entityTypes: EntityType[]
  /** Default refresh in ms; 0 = static. */
  refreshInterval: number
  freshness: Freshness
  geographicCoverage: string
  license: string
  licenseStatus: LicenseStatus
  /** Short credit line displayed in the UI. */
  attribution: string
  reliability: 'high' | 'medium' | 'low'
  access: Access
  /**
   * True when the source publishes no reuse licence (or reserves rights) and permission from the
   * provider has been requested but not yet granted. Shown in the UI as "unofficial / pending".
   */
  permissionPending?: boolean
  /** Only usable for non-commercial projects (Andorra View is non-commercial). */
  nonCommercialOnly?: boolean
  notes?: string
}

const MIN = 60_000

export const DATA_SOURCES = {
  // ---------------------------------------------------------------- global live feeds
  'adsb-lol': {
    id: 'adsb-lol',
    name: 'adsb.lol',
    organization: 'adsb.lol community network',
    url: 'https://adsb.lol',
    endpoint: 'https://api.adsb.lol/v2/lat/{lat}/lon/{lon}/dist/{nm}',
    entityTypes: ['aircraft'],
    refreshInterval: 10_000,
    freshness: 'live',
    geographicCoverage: 'Global (receiver-dependent); 110 km around Andorra requested',
    license: 'ODbL 1.0',
    licenseStatus: 'open-data',
    attribution: 'Aircraft: adsb.lol (ODbL)',
    reliability: 'medium',
    access: 'proxy',
    notes: 'No CORS → proxied with ~8 s cache. Low-level coverage inside the valleys depends on volunteer receivers.',
  },
  opensky: {
    id: 'opensky',
    name: 'OpenSky Network',
    organization: 'OpenSky Network association',
    url: 'https://opensky-network.org',
    endpoint: 'https://opensky-network.org/api/states/all?lamin&lomin&lamax&lomax',
    entityTypes: ['aircraft'],
    refreshInterval: 30_000,
    freshness: 'live',
    geographicCoverage: 'Global; bbox around Andorra requested',
    license: 'OpenSky terms: non-profit research, education or government use',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Aircraft: The OpenSky Network',
    reliability: 'medium',
    access: 'proxy',
    nonCommercialOnly: true,
    notes: 'Fallback when adsb.lol fails. 400 credits/day anonymous, 4000 with OAuth2 client credentials.',
  },
  celestrak: {
    id: 'celestrak',
    name: 'CelesTrak GP (OMM JSON)',
    organization: 'CelesTrak',
    url: 'https://celestrak.org',
    endpoint: 'https://celestrak.org/NORAD/elements/gp.php?GROUP={group}&FORMAT=json',
    entityTypes: ['satellite'],
    refreshInterval: 120 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: 'Global orbital elements; positions propagated in the browser with satellite.js',
    license: 'Public orbital data; CelesTrak usage policy (fetch at most once per 2 h update)',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Orbital elements: CelesTrak',
    reliability: 'high',
    access: 'proxy',
    notes: 'OMM JSON is required: TLE cannot carry 6-digit catalogue numbers (exhausted 2026-07).',
  },
  'nasa-firms': {
    id: 'nasa-firms',
    name: 'NASA FIRMS active fires (VIIRS)',
    organization: 'NASA LANCE / FIRMS',
    url: 'https://firms.modaps.eosdis.nasa.gov',
    endpoint: 'https://firms.modaps.eosdis.nasa.gov/data/active_fire/{sensor}/csv/{FILE}_Europe_24h.csv',
    entityTypes: ['fire'],
    refreshInterval: 15 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: 'Europe 24 h files filtered to 150 km around Andorra',
    license: 'NASA open data (acknowledgement requested)',
    licenseStatus: 'open-data',
    attribution: 'Fires: NASA FIRMS (LANCE)',
    reliability: 'high',
    access: 'proxy',
    notes: 'Satellite hotspots, ~3 h latency after overpass. Thermal anomalies are not all wildfires.',
  },
  emsc: {
    id: 'emsc',
    name: 'EMSC FDSN event service',
    organization: 'European-Mediterranean Seismological Centre',
    url: 'https://www.seismicportal.eu',
    endpoint: 'https://www.seismicportal.eu/fdsnws/event/1/query?format=json&lat&lon&maxradius&starttime',
    entityTypes: ['earthquake'],
    refreshInterval: 2 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: 'Euro-Mediterranean; aggregates IGN (ES) and ReNaSS (FR) small Pyrenean events',
    license: 'EMSC data policy — free with attribution (exact licence text UNVERIFIED)',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Earthquakes: EMSC (incl. IGN, ReNaSS)',
    reliability: 'high',
    access: 'direct',
    notes: 'USGS returned 0 events within 100 km for the last year, so EMSC is the primary source.',
  },
  meteoalarm: {
    id: 'meteoalarm',
    name: 'Meteoalarm warnings — Andorra',
    organization: 'EUMETNET / Servei Meteorològic Nacional d’Andorra',
    url: 'https://meteoalarm.org',
    endpoint: 'https://feeds.meteoalarm.org/api/v1/warnings/feeds-andorra',
    entityTypes: ['weatherAlert'],
    refreshInterval: 5 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: 'Andorra warning zones (nord, centre, sud)',
    license: 'Meteoalarm terms (“equivalent to CC BY 4.0” + redistribution terms)',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Warnings: Meteoalarm / SMN Andorra',
    reliability: 'high',
    access: 'proxy',
  },
  eaws: {
    id: 'eaws',
    name: 'EAWS avalanche danger ratings',
    organization: 'European Avalanche Warning Services / BPA Andorra',
    url: 'https://www.avalanches.org',
    endpoint: 'https://static.avalanche.report/eaws_bulletins/{date}/{date}.ratings.json',
    entityTypes: ['avalancheZone'],
    refreshInterval: 30 * MIN,
    freshness: 'periodic',
    geographicCoverage: 'Andorra micro-regions AD-01…AD-03',
    license: 'EAWS open data (CC BY 4.0 per avalanches.org; verify per region)',
    licenseStatus: 'open-data',
    attribution: 'Avalanche danger: EAWS / SMN Andorra',
    reliability: 'medium',
    access: 'direct',
    notes: 'Seasonal: published roughly December–May.',
  },
  'open-meteo': {
    id: 'open-meteo',
    name: 'Open-Meteo forecast',
    organization: 'Open-Meteo.com',
    url: 'https://open-meteo.com',
    endpoint: 'https://api.open-meteo.com/v1/forecast',
    entityTypes: ['weatherStation'],
    refreshInterval: 15 * MIN,
    freshness: 'periodic',
    geographicCoverage: 'Global model grid; queried per point',
    license: 'Data CC BY 4.0; free API non-commercial only',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Forecast: Open-Meteo.com (CC BY 4.0)',
    reliability: 'high',
    access: 'direct',
    nonCommercialOnly: true,
    notes: 'Model output, not observations — always labelled as forecast.',
  },

  // ---------------------------------------------------------------- Andorran sources
  'meteo-ad': {
    id: 'meteo-ad',
    name: 'SMN — observacions actuals',
    organization: 'Servei Meteorològic Nacional (Govern d’Andorra)',
    url: 'https://www.meteo.ad',
    endpoint: 'https://www.meteo.ad/home/DadesActuals?idioma=0&pestanya={n}&privat=false',
    entityTypes: ['weatherStation'],
    refreshInterval: 10 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: 'About 30 automatic stations in Andorra',
    license: 'No reuse licence published',
    licenseStatus: 'publicly-accessible',
    attribution: 'Observacions: Servei Meteorològic Nacional d’Andorra',
    reliability: 'medium',
    access: 'proxy',
    permissionPending: true,
    notes: 'Undocumented endpoint behind the meteo.ad map. Official JSON access is by request form.',
  },
  'mobilitat-incidents': {
    id: 'mobilitat-incidents',
    name: 'Mobilitat — incidències',
    organization: 'Departament de Mobilitat (Govern d’Andorra)',
    url: 'https://www.mobilitat.ad',
    endpoint: 'https://app.mobilitat.ad/api/v1/incidents/ca',
    entityTypes: ['trafficIncident', 'roadClosure'],
    refreshInterval: 2 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: 'Andorran road network',
    license: 'mobilitat.ad legal notice: all rights reserved, personal use',
    licenseStatus: 'publicly-accessible',
    attribution: 'Incidències: Mobilitat Andorra',
    reliability: 'medium',
    access: 'proxy',
    permissionPending: true,
  },
  'mobilitat-cameras': {
    id: 'mobilitat-cameras',
    name: 'Mobilitat — càmeres de trànsit',
    organization: 'Departament de Mobilitat (Govern d’Andorra)',
    url: 'https://www.mobilitat.ad',
    endpoint: 'https://app.mobilitat.ad/api/v1/cameras → https://imgs.mobilitat.ad/prod/{name}.gif',
    entityTypes: ['webcam'],
    refreshInterval: 2 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: '69 road cameras incl. Spanish and French borders',
    license: 'mobilitat.ad legal notice: all rights reserved, personal use',
    licenseStatus: 'publicly-accessible',
    attribution: 'Càmeres: Mobilitat Andorra',
    reliability: 'medium',
    access: 'proxy',
    permissionPending: true,
    notes: 'Animated GIF timelapses (~1.2 MB) refreshed every few minutes.',
  },
  'mobilitat-points': {
    id: 'mobilitat-points',
    name: 'Mobilitat — aparcaments i recàrrega',
    organization: 'Departament de Mobilitat (Govern d’Andorra)',
    url: 'https://www.mobilitat.ad',
    endpoint: 'https://app.mobilitat.ad/api/v1/points/ca',
    entityTypes: ['parking', 'evCharger'],
    refreshInterval: 60 * MIN,
    freshness: 'periodic',
    geographicCoverage: '71 car parks, 27 EV charging sites',
    license: 'mobilitat.ad legal notice: all rights reserved, personal use',
    licenseStatus: 'publicly-accessible',
    attribution: 'Aparcaments: Mobilitat Andorra',
    reliability: 'medium',
    access: 'proxy',
    permissionPending: true,
    notes: 'Static capacity (no live occupancy).',
  },
  'alv-parking': {
    id: 'alv-parking',
    name: 'Aparcaments comunals — ocupació',
    organization: 'Comú d’Andorra la Vella',
    url: 'https://www.andorralavella.ad',
    endpoint: 'https://sit.andorralavella.ad/server/rest/services/Aparcaments/AparcamentsComunals_SQLserver/FeatureServer/0/query',
    entityTypes: ['parking'],
    refreshInterval: 2 * MIN,
    freshness: 'near-real-time',
    geographicCoverage: '36 municipal car parks, 13 with occupancy',
    license: 'No reuse licence published',
    licenseStatus: 'publicly-accessible',
    attribution: 'Ocupació: Comú d’Andorra la Vella',
    reliability: 'low',
    access: 'direct',
    permissionPending: true,
    notes: 'Update frequency UNVERIFIED (values unchanged over 10 min during research).',
  },
  'aire-ad': {
    id: 'aire-ad',
    name: 'Qualitat de l’aire',
    organization: 'Àrea de Medi Ambient (Govern d’Andorra)',
    url: 'https://aire.ad',
    endpoint: 'https://aire.ad/api/web/mapData + /web/stations',
    entityTypes: ['airQuality'],
    refreshInterval: 30 * MIN,
    freshness: 'periodic',
    geographicCoverage: 'Air quality network (4–7 stations)',
    license: 'No reuse licence published',
    licenseStatus: 'publicly-accessible',
    attribution: 'Qualitat de l’aire: Govern d’Andorra',
    reliability: 'medium',
    access: 'proxy',
    permissionPending: true,
    notes: 'Same stations are reported to the EEA (open data) as an alternative.',
  },
  feda: {
    id: 'feda',
    name: 'FEDA — energia diària',
    organization: 'Forces Elèctriques d’Andorra',
    url: 'https://www.feda.ad',
    endpoint: 'https://www.feda.ad/oficina-virtual/api/GetLastEnergy',
    entityTypes: [],
    refreshInterval: 60 * MIN,
    freshness: 'periodic',
    geographicCoverage: 'National totals (daily, D-1)',
    license: 'No reuse licence published',
    licenseStatus: 'publicly-accessible',
    attribution: 'Energia: FEDA',
    reliability: 'medium',
    access: 'proxy',
    permissionPending: true,
  },
  'govern-sig': {
    id: 'govern-sig',
    name: 'SIG Govern d’Andorra (ArcGIS)',
    organization: 'Àrea de Cartografia (Govern d’Andorra)',
    url: 'https://sig.govern.ad',
    endpoint: 'https://sig.govern.ad/server/rest/services/{folder}/{service}',
    entityTypes: ['boundary', 'road', 'busStop', 'busLine'],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Andorra',
    license: 'No general licence; some layers forbid commercial use without authorisation',
    licenseStatus: 'publicly-accessible',
    attribution: 'Base topogràfica cedida pel Govern d’Andorra',
    reliability: 'high',
    access: 'snapshot',
    permissionPending: true,
  },
  'govern-dtm': {
    id: 'govern-dtm',
    name: 'MDT 5 m (ArcGIS elevation cache)',
    organization: 'Àrea de Cartografia (Govern d’Andorra)',
    url: 'https://sig.govern.ad',
    endpoint: 'https://sig.govern.ad/server/rest/services/IDE/Andorra_DTM_5m_WGS84/ImageServer',
    entityTypes: [],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Andorra only',
    license: 'No general licence published',
    licenseStatus: 'publicly-accessible',
    attribution: 'Relleu: Govern d’Andorra',
    reliability: 'high',
    access: 'tiles',
    permissionPending: true,
  },
  'govern-ortho': {
    id: 'govern-ortho',
    name: 'Ortofoto 2022 (tile cache)',
    organization: 'Àrea de Cartografia (Govern d’Andorra)',
    url: 'https://sig.govern.ad',
    endpoint: 'https://sig.govern.ad/server/rest/services/Hosted/Mapa_Base_IDE_Orto_2022_WM/MapServer',
    entityTypes: [],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Andorra only',
    license: 'No general licence published',
    licenseStatus: 'publicly-accessible',
    attribution: 'Ortofoto: Govern d’Andorra',
    reliability: 'high',
    access: 'tiles',
    permissionPending: true,
  },
  osm: {
    id: 'osm',
    name: 'OpenStreetMap',
    organization: 'OpenStreetMap contributors',
    url: 'https://www.openstreetmap.org',
    endpoint: 'https://overpass-api.de/api/interpreter (build-time snapshot)',
    entityTypes: ['place'],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Andorra',
    license: 'ODbL 1.0',
    licenseStatus: 'open-data',
    attribution: '© OpenStreetMap contributors',
    reliability: 'high',
    access: 'snapshot',
  },
  'eox-s2cloudless': {
    id: 'eox-s2cloudless',
    name: 'Sentinel-2 cloudless 2024',
    organization: 'EOX IT Services',
    url: 'https://s2maps.eu',
    endpoint: 'https://tiles.maps.eox.at/wmts',
    entityTypes: [],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Global (context outside Andorra)',
    license: 'CC BY-NC-SA 4.0 (non-commercial)',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Sentinel-2 cloudless – https://s2maps.eu by EOX IT Services GmbH (Contains modified Copernicus Sentinel data 2024)',
    reliability: 'high',
    access: 'tiles',
    nonCommercialOnly: true,
  },
  'aws-terrain': {
    id: 'aws-terrain',
    name: 'Terrain Tiles (Terrarium)',
    organization: 'AWS Open Data / Mapzen',
    url: 'https://registry.opendata.aws/terrain-tiles/',
    endpoint: 'https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png',
    entityTypes: [],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Global',
    license: 'Open (EU-DEM © Copernicus, SRTM public domain)',
    licenseStatus: 'open-data',
    attribution: 'Relleu fora d’Andorra: Mapzen Terrain Tiles (EU-DEM, SRTM)',
    reliability: 'high',
    access: 'tiles',
  },
  'google-3d': {
    id: 'google-3d',
    name: 'Google Photorealistic 3D Tiles',
    organization: 'Google',
    url: 'https://developers.google.com/maps/documentation/tile/3d-tiles',
    endpoint: 'https://tile.googleapis.com/v1/3dtiles/root.json?key=…',
    entityTypes: [],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Global where Google has 3D mesh (Andorra coverage UNVERIFIED)',
    license: 'Google Maps Platform terms (no caching, attribution required)',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Google',
    reliability: 'high',
    access: 'tiles',
    notes: 'Optional, only when VITE_GOOGLE_MAPS_API_KEY is set. 1,000 free root requests/month.',
  },
  'cesium-ion': {
    id: 'cesium-ion',
    name: 'Cesium World Terrain',
    organization: 'Cesium GS',
    url: 'https://cesium.com/platform/cesium-ion/',
    endpoint: 'Cesium ion asset 1',
    entityTypes: [],
    refreshInterval: 0,
    freshness: 'static',
    geographicCoverage: 'Global',
    license: 'Cesium ion Community plan (non-commercial)',
    licenseStatus: 'licensed-redistribution',
    attribution: 'Cesium ion',
    reliability: 'high',
    access: 'tiles',
    nonCommercialOnly: true,
    notes: 'Optional, only when VITE_CESIUM_ION_TOKEN is set.',
  },
} as const satisfies Record<string, DataSource>

export type SourceId = keyof typeof DATA_SOURCES

export function getSource(id: string): DataSource | undefined {
  return (DATA_SOURCES as Record<string, DataSource>)[id]
}
